services:
  httpd:
    container_name: Webshop
    image: httpd:latest
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./src
        target: /usr/local/apache2/htdocs/
volumes: 
  src: 